import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";
import ReduxProvider from "@/lib/reduxProvider";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "@/ui/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
      <Navbar />

        <ReduxProvider>
          
          {children}</ReduxProvider>
      </body>
    </html>
  );
}
