import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";
import ReduxProvider from "@/lib/reduxProvider";
import { Inter as FontSans } from "next/font/google"
import Navbar from "@/ui/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  suppressHydrationWarning={true}>
      <Navbar />

        <ReduxProvider>
          
          {children}</ReduxProvider>
      </body>
    </html>
  );
}
